### ISSUE TITLE
Missed spell in C2E21

### ISSUE THREAD

**Issue by pcordes** [snappdragonn/CritRoleHpTracker#5]
At 1:41:16, Jester casts Speak With Dead (3rd).  It's not a ritual so she had to spend a spell slot, but the tracker still shows her with  both lvl3 slots available.

Critrolestats has a spreadsheet of all spells cast during the campaign (https://www.critrolestats.com/stats-wm links https://docs.google.com/spreadsheets/d/1KXdTxewHmnBr6XTsX5pbUqZ9ObR4inZsgbaCQbMl7lc/edit#gid=1731680363), so that might be a useful cross-check for your data.  It includes the Speak With Dead.

On reloading the video (F5) to double-check, the tracker showed Beau with full HP after the troll fight, too, and didn't show Jester having spent a 1st-level slot on Healing Word during the fight.  After seeking around some, it seemed to get back in sync, so I guess that's a separate maybe-bug?

**Comment by pcordes** [comment]
Later in the episode (3:12:00), during the fish-men fight, Jester's 1st-level spell slots are showing as re-filled.  I think I just hit play from a point where it was showing 1 spent from Healing Word, but maybe an add played and made it have to find its place again.

Seeking back to the troll fight and then forward again, I'm now seeing 1 spend 1st level and 1 spend 3rd level, which is correct at 3:12:00.  Maybe you fixed the original and something got messed up in loading the new data?  Or maybe the original problem was also something other than the original data.

FYI, I haven't updated Chromium with it since July 23, but I did `git pull` in the directory I originally pointed it at more recently, like Oct 28.  IDK if Chromium copies the extension code into my home directory or if it will notice updates here.  (I have restarted Chromium since the last git pull.)

**Comment by snappdragonn** [comment]
The speak with dead spell I have 20 seconds later at 1:41:39.

The problem with Beau's hp and Jesters spells resetting is from an error occurring when Calianna cast a spell and the tracker tries to update her spell slots but its not tracking her so it can't (I'm giving descriptions of her spells but not actually tracking her because I didn't want to add a whole new character for only one episode). This doesn't cause any other problems when watching the video normally so that the events (like hp updating or spells cast) happen one at a time but when skipping forward or backward in the episode it processes multiple events at once so an error with one of them stops the tracker processing any events after that. This means for skipping forwards in the episode the tracker doesn't update and for skipping backwards (where it redoes all events from the start again) it undoes everything thus Jester regains spell slots and Beau regains her hp.
Thank you for mentioning this as I probably wouldn't have noticed otherwise :)

I've fixed the data so that it won't try to update Caliannas spell slots so it should work now. I've also added a try-catch so any other errors with processing events shouldn't cause the same problem in the future but that's just in the dev branch for now.


I hadn't thought about how ads would effect the tracker. I'm so used to ad block that it didn't cross my mind, I will have to test it. Thank you for mentioning that.
